apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-csi-snapshot-controller-operator
  name: openshift-csi-snapshot-controller-operator-config
data:
  operator-config.yaml: |
    apiVersion: operator.openshift.io/v1alpha1
    kind: GenericOperatorConfig
