apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-snapshot-controller-operator-sa
  namespace: openshift-csi-snapshot-controller-operator
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
