apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-snapshot-controller-sa
  namespace: openshift-csi-snapshot-controller
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
